// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  heading: dynamic(() => import("./Titles")),
  quote: dynamic(() => import("./Quote")),
};
