// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  blog_post: dynamic(() => import("./BlogPost")),
  heading: dynamic(() => import("./Titles")),
  image: dynamic(() => import("./Image")),
  quote: dynamic(() => import("./Quote")),
  text: dynamic(() => import("./Text")),
  text_with_image: dynamic(() => import("./TextWithImage")),
  video: dynamic(() => import("./Video")),
};
